stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/pre_processing.py
    deps:
    - src/pre_processing.py
    - data/raw
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/feature_eng.py
    deps:
    - src/feature_eng.py
    - data/interim
    params:
    - feature_engineering.max_features
    outs:
    - data/processed

  model_building:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/processed
    params:
    - model_building.n_estimators
    - model_building.random_state
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_eval.py
    deps:
    - src/model_eval.py
    - models/model.pkl
    - data/processed
    outs:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
